[local]
localhost 

[mongodb]
mongodb-dev.paws-88s.online

[catalogue]
catalogue-dev.paws-88s.online

[redis]
redis-dev.paws-88s.online

[user]
user-dev.paws-88s.online

[cart]
cart-dev.paws-88s.online

[mysql]
mysql-dev.paws-88s.online

[shipping]
shipping-dev.paws-88s.online

[rabbitmq]
rabbitmq-dev.paws-88s.online

[payment]
payment-dev.paws-88s.online

[frontend]
frontend-dev.paws-88s.online

